### PR TITLE
feat(Menu): attachment styles

### PR DESCRIPTION
**Pull request by AriLFrankel**
Attachment styles: everyone's a little different.

Accept props for bottom and right attachments, as well as upwards and downwards opening

attachBottom: align top of menu with bottom of anchor
openUp: open the menu upwards, align the bottom of the menu with the bottom of the anchor
openLeft: open the menu leftwards, align the right of the menu with the right of the anchor

Defaults: attaches Top Left, opens Right Down

### CODE REVIEW

**Comment by AriLFrankel** [comment]
@martahj added examples

**Comment by martahj** [comment]
Very cool. I think I'm having trouble seeing how these differ because they're all at the bottom of the page, could we walk through these tomorrow?

**Comment by martahj** [comment]
When the menu doesn't cover the button, clicking on the button closes and then re-opens the menu. Is this the expected behavior?

**Comment by AriLFrankel** [comment]
Good catch. That was a regression. Fix pushed

**Pull request merged**
