### PR TITLE
Tooltip fix

### PR DESCRIPTION
**Pull request by dekkofilms**
This does remove a lot of unneeded babel installs in our dev dependencies, so would love some additional eyes on that. Also, bumps `react`, `react-dom`, `next`, and `now` back up. The .babelrc file has been extremely simplified as well. 

Commit one should have the tooltip fix in it. There seemed to be some build differences/packages that were affecting the tooltip from functioning properly.

### Summary of changes:
 - Fixes tooltip
 - Ran lint fix with new prettier config

### Behaviors that should be QA'd:
 - Drawers page is still good
 - Tooltips should be fixed to its former glory. 🙂 

### Github Issues closed by this PR:
 - Resolves issue found in #315

### CODE REVIEW

**Comment by dekkofilms** [comment]
@martahj I'm definitely on board for that!

**Comment by martahj** [comment]
@dekkofilms Looks like circle is failing on the `yarn install` step because of an `SyntaxError: Unexpected token import` error; likely related to the updated dependencies

**Comment by dekkofilms** [comment]
I will take a look at this now @martahj

**Comment by dekkofilms** [comment]
@martahj after tinkering with package dependencies and `.babelrc` this is now deployed and ready!

**Comment by brad-decker** [comment]
Can you provide a little more details about what this actually changes? I thought we didn't have prettier installed in this repo due to its *huge* issues with inline css?

**Comment by brad-decker** [comment]
hey team, see me today. We have some serious issues in this code base that aren't fixed by this.

**Comment by dekkofilms** [comment]
@brad-decker sure! Prettier wasn't installed in this PR, I believe it came in with the first big introduction to flow, eslint, testing, etc. And in a previous PR, I did add a config file (to at least match our standard). This PR did run yarn lint --fix in order to QA everything and make sure nothing was broken.

All that is happening in this PR is mainly ripping out unneeded babel packages based on nextjs documentation/best practices, and tweaking our `.babelrc` file in a more simplistic way. Also, it bumped back up our react, react-dom, and next versions back up. They were all downgraded in the big flow, eslint, testing PR ... and this puts them back up.

**Comment by dekkofilms** [comment]
RIP

**Pull request closed without merging**
