### PR TITLE
feat(icon): add onClick

### PR DESCRIPTION
**Pull request by petegivens**
This PR allows Icon to accept an `onClick` function. Previously, we've been wrapping the icons in divs to accommodate onClick functions.

### CODE REVIEW

**Comment by martahj** [comment]
Sweet!

Since we're temporarily unable to use Now, could you please do the following:
* Pull in the latest changes
* Run `yarn dev`
* Verbally verify that this is behaving as expected

**Comment by petegivens** [comment]
@martahj yes, I have pulled down latest changes and verified that it's working. One thought--while I'm add it, do you think there's value in also adding `onMouseUp` and `onMouseDown` props?

**Comment by martahj** [comment]
@petegivens What would be the use case?

**Comment by petegivens** [comment]
@martahj i don't have any specific use-case in mind, just thought it might give more granular control to the user. but then i guess we could talk about onKeyPress and all kinds of stuff so maybe there's no need :)

**Comment by martahj** [comment]
I don't see a huge need for it, though it probably wouldn't hurt anything

**Comment by petegivens** [comment]
Let's just leave it as-is until we find a need for it

**Pull request merged**
